import { Certification } from "../models/certification";

export const CERTIFICATIONS: Certification[] = [
  {
    id: 1,
    name: "ACA",
    link: "",
    description: "Adobe Certified Associate",
  },
  {
    id: 2,
    name: "ACE",
    link: "https://www.comptia.org/certifications/it-fundamentals",
    description:
      "Great for helping someone learn if IT is a good fit for them.",
  },
  {
    id: 3,
    name: "ACI",
    link:
      "https://elearning.adobe.com/2019/05/path-becoming-adobe-certified-instructor-aci/",
    description: "Adobe Certified Instructor",
  },
  {
    id: 4,
    name: "ACMP",
    link: "",
    description: "Aruba Certified Mobility \nProfessional",
  },
  {
    id: 5,
    name: "ASE/CSE",
    link: "",
    description: "Adobe Certified Expert",
  },
  {
    id: 6,
    name: "AWS",
    link: "",
    description:
      "Amazon Web Services: Certified Solutions Architect - \nAssociate",
  },
  {
    id: 7,
    name: "AWS",
    link: "",
    description:
      "Amazon Web Services: Certified SysOps Administrator - \nAssociate",
  },
  {
    id: 8,
    name: "AWS",
    link: "",
    description:
      "Amazon Web Services: Certified Solutions Architect -\nProfessional",
  },
  {
    id: 9,
    name: "AWS",
    link: "",
    description:
      "Amazon Web Services: Certified DevOps Engineer-\nProfessional",
  },
  {
    id: 10,
    name: "CASP",
    link: "",
    description: "CompTIA Advanced Security\nPractitioner",
  },
  {
    id: 11,
    name: "CCA",
    link: "",
    description: "Citrix Certifed Administrator",
  },
  {
    id: 12,
    name: "CCDP",
    link: "",
    description: "CCDP: Cisco Certified Design Professional",
  },
  {
    id: 13,
    name: "CCIA",
    link: "",
    description: "Citrix Certified Integration Architect",
  },
  {
    id: 14,
    name: "CCIE",
    link: "",
    description: "Cisco Certified Internetwork \nExpert",
  },
  {
    id: 15,
    name: "CCNA",
    link:
      "https://www.infosecinstitute.com/courses/ccna-4cert-training/?utm_source=GoogleAds&utm_campaign=Google%20AdWords%20Cisco&utm_medium=PPC&utm_content=393694050840&utm_term=online%20cisco%20certification&matchtype=b&network=g&device=c&gclid=Cj0KCQjwx7zzBRCcARIsABPRscM2jzPa8qYP9gpXZdrU-e5xXSCbPOzEDlbtDdj5mVMR3Wyopy9SH_saAkxcEALw_wcB",
    description: "Cisco Certified Network Associate",
  },
  {
    id: 16,
    name: "CCNP",
    link: "",
    description: "Cisco Certified Network\nProfessional",
  },
  {
    id: 17,
    name: "CCNP Wireless",
    link: "",
    description: "Cisco Certified Network \nProfessional",
  },
  {
    id: 18,
    name: "CCP",
    link: "",
    description: "Cloud Certified Professional",
  },
  {
    id: 19,
    name: "CCP-M",
    link: "",
    description: "Cloud Certified Professional",
  },
  {
    id: 20,
    name: "CCSK",
    link: "",
    description: "Cloud Certified Professional",
  },
  {
    id: 21,
    name: "CEH",
    link: "",
    description: "Certified Ethical Hacker",
  },
  {
    id: 22,
    name: "CGEIT",
    link: "",
    description: "Certified in the Governance of \nEnterprise IT",
  },
  {
    id: 23,
    name: "CHFI",
    link: "",
    description: "Computer Hacking Forensic \nInvestigator",
  },
  {
    id: 24,
    name: "CISA",
    link: "",
    description: "Certified Information \nSystems Auditor",
  },
  {
    id: 25,
    name: "Cisco Certified DevNet Associate",
    link: "",
    description: "",
  },
  {
    id: 26,
    name: "Cisco Certified DevNet Professional",
    link: "",
    description: "",
  },
  {
    id: 27,
    name: "Cisco Certified Specialist",
    link: "",
    description: "",
  },
  {
    id: 28,
    name: "CISM",
    link: "",
    description: "Certified Information \nSecurity Manager",
  },
  {
    id: 29,
    name: "CISSP",
    link: "",
    description: "Certified Information Systems \nSecurity Professional",
  },
  {
    id: 30,
    name: "CNE",
    link: "",
    description: "Certified Information Systems \nSecurity Professional",
  },
  {
    id: 31,
    name: "CompTIA A+",
    link: "",
    description:
      "Great starter certifications that has helped launch over 2 million IT careers.",
  },
  {
    id: 32,
    name: "CompTIA Cloud Essentials",
    link: "",
    description: "Starting network certification",
  },
  {
    id: 33,
    name: "CompTIA Cloud+",
    link: "",
    description: "Intermediate network certification",
  },
  {
    id: 34,
    name: "CompTIA CTT+",
    link: "",
    description: "Certified Technical \nTrainer",
  },
  {
    id: 35,
    name: "CompTia CySA+",
    link: "",
    description: "Cybersecurity Analyst",
  },
  {
    id: 36,
    name: "CompTIA IT Fundamentals +",
    link: "",
    description: "Starting network certification",
  },
  {
    id: 37,
    name: "CompTIA Linux+/LPIC-1",
    link: "",
    description: "Intermediate network certification",
  },
  {
    id: 38,
    name: "CompTIA Network+",
    link: "",
    description: "Intermediate certification",
  },
  {
    id: 39,
    name: "CompTIA PenTest+",
    link: "",
    description: "Advanced IS certification",
  },
  {
    id: 40,
    name: "CompTIA Security+",
    link: "",
    description: "Intermediate IS certification",
  },
  {
    id: 41,
    name: "CompTIA Server+",
    link: "",
    description: "Intermediate certification",
  },
  {
    id: 42,
    name: "CPTE",
    link: "",
    description: "Certified Penetration \nTesting Engineer",
  },
  {
    id: 43,
    name: "CSP",
    link: "",
    description: "Certified Scrum Professional",
  },
  {
    id: 44,
    name: "CSSLP",
    link: "",
    description: "Certified Secure Software \nLifecycle Professional",
  },
  {
    id: 45,
    name: "CWNA",
    link: "",
    description: "Certified Wireless Network \nAdministrator",
  },
  {
    id: 46,
    name: "CWTS",
    link: "",
    description: "Certified Wireless Technology \nSpecialist",
  },
  {
    id: 47,
    name: "Docker Kubernetes",
    link: "",
    description: "",
  },
  {
    id: 48,
    name: "Framework 2 Certification",
    link: "",
    description: "Zend Framework 2 Certification",
  },
  {
    id: 49,
    name: "GCED",
    link: "",
    description: "",
  },
  {
    id: 50,
    name: "GCIH",
    link: "",
    description: "GIAC Certified Incident Handler",
  },
  {
    id: 51,
    name: "GCPCA",
    link: "",
    description: "Google Certified Professional \nCloud Architect",
  },
  {
    id: 52,
    name: "GISP",
    link: "",
    description: "GIAC Information Security \nProfessional",
  },
  {
    id: 53,
    name: "GSEC",
    link: "",
    description: "GIAC Security Essentials",
  },
  {
    id: 54,
    name: "GSLC",
    link: "",
    description: "",
  },
  {
    id: 55,
    name: "HCIE",
    link: "",
    description: "Huawei Certified Internetwork \nExpert",
  },
  {
    id: 56,
    name: "HCNA",
    link: "",
    description: "Huawei Certified Network \nAssociate",
  },
  {
    id: 57,
    name: "HCNP",
    link: "",
    description: "Huawei Certified Network \nProfessional",
  },
  {
    id: 58,
    name: "HDI DST",
    link: "",
    description: "Huawei Certified Network \nProfessional",
  },
  {
    id: 59,
    name: "HDI CI",
    link: "",
    description: "HDI Certified Instructor",
  },
  {
    id: 60,
    name: "HDI DSM",
    link: "",
    description: "HDI Desktop Support Manager",
  },
  {
    id: 61,
    name: "HDI SCA",
    link: "",
    description: "HDI Support Center Analyst",
  },
  {
    id: 62,
    name: "HDI SCM",
    link: "",
    description: "HDI Support Center Manager",
  },
  {
    id: 63,
    name: "IBM Certified Specialist",
    link: "",
    description: "Intermediate storage and data certification",
  },
  {
    id: 64,
    name: "ITIL Expert",
    link: "",
    description: "Advanced hardware, services, and infastructure",
  },
  {
    id: 65,
    name: "ITIL Foundation",
    link: "",
    description: "Starter hardware, services and infastructure",
  },
  {
    id: 66,
    name: "ITIL Intermediate",
    link: "",
    description: "Intermediate hardware, services, and infastructure",
  },
  {
    id: 67,
    name: "ITIL Master",
    link: "",
    description: "Expert hardware, services, and infastructure",
  },
  {
    id: 68,
    name: "Linux Essentials",
    link: "",
    description: "Linux Essentials Beginner/Novice",
  },
  {
    id: 69,
    name: "LPIC-1",
    link: "",
    description: "Linux Professional Intermediate",
  },
  {
    id: 70,
    name: "LPIC-2",
    link: "",
    description: "Linux Professional Advanced",
  },
  {
    id: 71,
    name: "LPIC-3",
    link: "",
    description: "Linux Professional Expert",
  },
  {
    id: 72,
    name: "MCSA",
    link: "",
    description: "Microsoft Certified Solutions Associate Intermediate",
  },
  {
    id: 73,
    name: "MCSA: Windows Server 2012",
    link: "",
    description: "Microsoft Windows Server 2012 Intermediate",
  },
  {
    id: 74,
    name: "MCSD",
    link: "",
    description: "Microsoft Certified Solutions Developer Advanced",
  },
  {
    id: 75,
    name: "MCSD Application Lifcycle Management",
    link: "",
    description: "Microsoft Application Lifecycle Management Advanced",
  },
  {
    id: 76,
    name: "MCSE",
    link: "",
    description: "Microsoft Certified Solutions Expert Advanced",
  },
  {
    id: 77,
    name: "MCSE Server Infrastruscure",
    link: "",
    description:
      "Microsoft Certified Solutions Expert Server Infrastructure Acvanced",
  },
  {
    id: 78,
    name: "MCT",
    link: "",
    description: "Microsoft Certified Trainer Intermediate",
  },
  {
    id: 79,
    name: "Microsoft Specialist",
    link: "",
    description: "",
  },
  {
    id: 80,
    name: "MTA",
    link: "",
    description: "Microsoft Technology Associate Beginner/Novice",
  },
  {
    id: 81,
    name: "OCA",
    link: "",
    description: "Oracle Certified Associate Intermediate",
  },
  {
    id: 82,
    name: "OCAJ",
    link: "",
    description: "Oracle Certified Associate, Java SE 6/SE5 Beginner/Novice",
  },
  {
    id: 83,
    name: "OCMJD",
    link: "",
    description: "Oracle Certified Master, Java SE6 Developer Advanced",
  },
  {
    id: 84,
    name: "OCMJEA",
    link: "",
    description:
      "Oracle Certified Master, Java EE 5 Enterprise Architect Expert",
  },
  {
    id: 85,
    name: "OCP",
    link: "",
    description: "Oracle Certified Professional Intermediate",
  },
  {
    id: 86,
    name: "OCPJP",
    link: "",
    description:
      "Oracle Certified Professional, Java SE 6/SE 5 Programmer Intermediate",
  },
  {
    id: 87,
    name: "OpenStack Administrator",
    link: "",
    description: "",
  },
  {
    id: 88,
    name: "PHP Certification",
    link: "",
    description: "Zend PHP Certification Intermediate",
  },
  {
    id: 89,
    name: "PMP",
    link: "",
    description: "PMI Project Professional Advanced",
  },
  {
    id: 90,
    name: "Prince2 Foundation",
    link: "",
    description:
      "Office of Government Commerce (OGC) Prince2 Foundation Intermediate",
  },
  {
    id: 91,
    name: "Prince2 Practitioner",
    link: "",
    description:
      "Office of Government Commerce (OGC) Prince2 Practitioner Expert",
  },
  {
    id: 92,
    name: "RCT",
    link: "",
    description: "Rackspace Certified Technician Intermediate",
  },
  {
    id: 93,
    name: "RHCA",
    link: "",
    description: "Red Hat Certified Architect Expert",
  },
  {
    id: 94,
    name: "RHCE",
    link: "",
    description: "Red Hat Certified Engineer Advanced Advanced",
  },
  {
    id: 95,
    name: "RHCSA",
    link: "",
    description: "Red Hat Certified System Administrator Intermediate",
  },
  {
    id: 96,
    name: "Salesforce.com",
    link: "",
    description: "Salesforce.com Certified Administrator Intermediate",
  },
  {
    id: 97,
    name: "SCA",
    link: "",
    description: "SUSE Certified Administrator Intermediate",
  },
  {
    id: 98,
    name: "SCE",
    link: "",
    description: "SUSE Certified Engineer Advanced",
  },
  {
    id: 99,
    name: "SCYBER",
    link: "",
    description:
      "Securing Cisco Network with Threat Detection and Analysis Expert",
  },
  {
    id: 100,
    name: "SEA",
    link: "",
    description: "SUSE Enterprise Architect Expert",
  },
  {
    id: 101,
    name: "Solutions Architect - Associate",
    link: "",
    description:
      "Amazon Web Services Certified Solutions Architect - Associate Intermediate",
  },
  {
    id: 102,
    name: "Solutions Architect - Professional",
    link: "",
    description:
      "Amazon Web Services Certified Solutions Architect - Professional Advanced",
  },
  {
    id: 103,
    name: "VCA",
    link: "",
    description: "VMware Certified Associate Beginner/Novice",
  },
  {
    id: 104,
    name: "VCA Workforce Mobility",
    link: "",
    description: "VMware Certified Associate Workforce Mobility Intermediate",
  },
  {
    id: 105,
    name: "VCDX",
    link: "",
    description: "Expert",
  },
  {
    id: 106,
    name: "VCIX",
    link: "",
    description: "Advanced",
  },
  {
    id: 107,
    name: "VCP",
    link: "",
    description: "VMware Certied Professional Intermediate",
  },
];
